name: CI Template

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      GH_PAT:
        required: true
      ARGOCD_SERVER:
        required: true
      ARGO_PASSWORD:
        required: true

env:
  NODE_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Lint code
        run: npm run lint
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run tests with coverage
        run: npm run test:cov
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  docker_build:
    runs-on: ubuntu-latest
    needs: test
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      CI_ENVIRONMENT_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kaniko
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${{ env.DOCKER_USERNAME }}\",\"password\":\"${{ env.DOCKER_PASSWORD }}\"}}}" > /kaniko/.docker/config.json

      - name: Build and push Docker image
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          FULL_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/microservice"
          TAG="${REPO_NAME}-${BRANCH_NAME}-${{ github.sha }}"

          /kaniko/executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "${FULL_IMAGE_NAME}:${TAG}" \
            --destination "${FULL_IMAGE_NAME}:${REPO_NAME}-${BRANCH_NAME}-latest"

  helm_update:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git yq

      - name: Clone Helm charts repository
        run: git clone https://${{ secrets.GH_PAT }}@github.com/WAYA-MULTI-LINK/waya-helm-charts.git

      - name: Update values file
        run: |
          cd waya-helm-charts
          git checkout main
          git pull origin main

          FILE_PATH="./microservices/${{ github.event.repository.name }}/${{ env.CI_ENVIRONMENT_NAME }}-values.yaml"
          REPO_NAME="${{ github.event.repository.name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          TAG="${REPO_NAME}-${BRANCH_NAME}-${{ github.sha }}"
          IMAGE_REPO="${{ secrets.DOCKER_USERNAME }}/microservice"

          if [ -f "$FILE_PATH" ]; then
            yq e -i ".application.image.repository = \"${IMAGE_REPO}:${TAG}\"" "$FILE_PATH"
            git config --global user.name "CI Bot"
            git config --global user.email "ci-bot@alerzo.com"
            git add "$FILE_PATH"
            git commit -m "Update Docker image tag to ${IMAGE_REPO}:${TAG}"
            git push https://${{ secrets.GH_PAT }}@github.com/WAYA-MULTI-LINK/waya-helm-charts.git HEAD:main
          else
            echo "File does not exist: $FILE_PATH"
            exit 1
          fi

  argocd_sync:
    runs-on: ubuntu-latest
    needs: helm_update
    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: admin
          ARGOCD_PASSWORD: ${{ secrets.ARGO_PASSWORD }}
        run: |
          argocd login "$ARGOCD_SERVER" \
            --username "$ARGOCD_USERNAME" \
            --password "$ARGOCD_PASSWORD" \
            --grpc-web --insecure

      - name: Sync application
        run: |
          TARGET_APP="${{ github.event.repository.name }}-${{ env.CI_ENVIRONMENT_NAME }}"
          argocd app sync "$TARGET_APP" \
            --server="${{ secrets.ARGOCD_SERVER }}" \
            --grpc-web --insecure
