name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      CI_ENVIRONMENT_NAME:
        description: "Environment to deploy to"
        required: true
        default: "development"

jobs:
  docker_build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      image_repo: ${{ steps.vars.outputs.image_repo }}
      slug: ${{ steps.vars.outputs.slug }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up build variables
        id: vars
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          FULL_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/microservice"
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG="${REPO_NAME}-${BRANCH_NAME}-${SHORT_SHA}"

          # Create slugified repo name
          REPO_SLUG=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "REPO_SLUG=${REPO_SLUG}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=${FULL_IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAG=${TAG}" >> $GITHUB_ENV

          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "image_repo=${FULL_IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "slug=${REPO_SLUG}" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }}:${{ env.TAG }} .
          docker push ${{ env.FULL_IMAGE_NAME }}:${{ env.TAG }}

  helm_update:
    runs-on: ubuntu-latest
    needs: docker_build
    env:
      CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
      IMAGE_TAG: ${{ needs.docker_build.outputs.tag }}
      IMAGE_REPO: ${{ needs.docker_build.outputs.image_repo }}
      REPO_SLUG: ${{ needs.docker_build.outputs.slug }}

    steps:
      - uses: actions/checkout@v3

      - name: Update Helm values
        run: |
          FILE_PATH="./microservices/${REPO_SLUG}/${CI_ENVIRONMENT_NAME}-values.yaml"
          echo "Updating $FILE_PATH with new image tag"
          yq e -i ".image.repository = \"${IMAGE_REPO}\"" "$FILE_PATH"
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" "$FILE_PATH"

      - name: Commit Helm values
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add microservices/${REPO_SLUG}/${CI_ENVIRONMENT_NAME}-values.yaml
          git commit -m "chore: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push

  argocd_sync:
    runs-on: ubuntu-latest
    needs: docker_build
    env:
      CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
      REPO_SLUG: ${{ needs.docker_build.outputs.slug }}

    steps:
      - name: Sync ArgoCD app
        run: |
          TARGET_APP="${REPO_SLUG}-${CI_ENVIRONMENT_NAME}"
          echo "Syncing $TARGET_APP"
          argocd app sync "$TARGET_APP" --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }} --insecure
